<?php

declare(strict_types=1);

/**
 * @var array<string>    $bad_user_agents
 * @var string           $base_path
 * @var string           $base_url
 * @var string           $sitemap_url
 * @var iterable<string> $trees
 */

?>
# robots.txt for <?= $base_url ?>

<?php if ($base_path !== '') : ?>
# CAUTION!  This robots.txt needs to be copied to the root folder.
<?php endif ?>

<?php foreach ($bad_user_agents as $bad_user_agent) : ?>
User-agent: <?= $bad_user_agent ?>

<?php endforeach ?>
Disallow: /

User-agent: *
Disallow: <?= $base_path ?>/admin
Disallow: <?= $base_path ?>/manager
Disallow: <?= $base_path ?>/editor
Disallow: <?= $base_path ?>/account

Disallow: <?= $base_path ?>/login   

Disallow: <?= $base_path ?>/mediafirewall.php
Disallow: <?= $base_path ?>/mediaviewer.php
Disallow: <?= $base_path ?>/module.php

Disallow: <?= $base_path ?>/public/*.png
Disallow: <?= $base_path ?>/tree/*?ajax=1

#2.0 links 
Disallow: <?= $base_path ?>/family.php
Disallow: <?= $base_path ?>/individual.php
Disallow: <?= $base_path ?>/source.php

# Noindex Pages blocked
Disallow: <?= $base_path ?>/tree/*/anniversary-ics
Disallow: <?= $base_path ?>/tree/*/contact
Disallow: <?= $base_path ?>/tree/*/hourglass-
Disallow: <?= $base_path ?>/tree/*/pedigree-
Disallow: <?= $base_path ?>/tree/*/relationships-

Disallow: <?= $base_path ?>/tree/*/location-list
Disallow: <?= $base_path ?>/tree/*/place-list
Disallow: <?= $base_path ?>/tree/*/repository-list
Disallow: <?= $base_path ?>/tree/*/source-list

Disallow: <?= $base_path ?>/module/tree/Chart/

Disallow: <?= $base_path ?>/tree/*/media-download
Disallow: <?= $base_path ?>/tree/*/media-list?
Disallow: <?= $base_path ?>/tree/*/media-thumbnail?

<?php foreach ($trees as $tree) : ?>
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/ancestors
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/calendar
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/compact
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/descendants
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/family-book
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/family-list
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/fan-chart
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/hourglass
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/individual-list
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/lifespans
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/pedigree
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/report
Disallow: <?= $base_path ?>/tree/<?= $tree ?>/timeline
<?php endforeach ?>

Crawl-delay: 2

<?php if ($sitemap_url !== '') : ?>
Sitemap: <?= $sitemap_url ?>
<?php endif ?>
